version: "3"
services:
  sshd:
    build: ./openssh-server
    ports: 
      - 22:22
      - 2222:2222
      - 5900:5900
    restart: always
    deploy:
      resources:
          limits:
            memory: 100M
    logging:
      options:
        max-size: 128k
